# Generated by Django 3.2.8 on 2021-12-09 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211208_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='alterado',
            new_name='changed',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='criado',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='publicado',
            new_name='published',
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('publicado', 'Publicado')], default='rascunho', max_length=10),
        ),
    ]
